package com.osps;

import com.osps.rips.FrmCargarRIPS;
import com.osps.rips.FrmAdministrarRIPS;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * @author Feisar Moreno
 * @date 21/02/2012
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    public FrmPrincipal() {
        initComponents();
        
        this.setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        mbrPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitCarga = new javax.swing.JMenuItem();
        mitAdministracion = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        mitAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OSPS - RIPS");

        panPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jMenu1.setText("Procesos");

        mitCarga.setText("Carga de archivos planos");
        mitCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCargaActionPerformed(evt);
            }
        });
        jMenu1.add(mitCarga);

        mitAdministracion.setText("Administración de periodos cargados");
        mitAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAdministracionActionPerformed(evt);
            }
        });
        jMenu1.add(mitAdministracion);

        mbrPrincipal.add(jMenu1);

        menAyuda.setText("Ayuda");

        mitAcercaDe.setText("Acerca de");
        mitAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAcercaDeActionPerformed(evt);
            }
        });
        menAyuda.add(mitAcercaDe);

        mbrPrincipal.add(menAyuda);

        setJMenuBar(mbrPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mitCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCargaActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.RIPS_CARGAR);
    }//GEN-LAST:event_mitCargaActionPerformed
    
    private void mitAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAdministracionActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.RIPS_ADMINISTRAR);
    }//GEN-LAST:event_mitAdministracionActionPerformed

    private void mitAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAcercaDeActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.ACERCA_DE);
    }//GEN-LAST:event_mitAcercaDeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.out.println(ex.getMessage());
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }
    
    public void abrirItemMenu(ItemsMenuPpal itemMenuPpal) {
        Component comps[] = this.panPrincipal.getComponents();
        int i = 0;
        while(comps != null && i < comps.length) {
            this.panPrincipal.remove(comps[i]);
            i++;
        }
        this.panPrincipal.revalidate();
        this.panPrincipal.repaint();
        
        switch (itemMenuPpal) {
            case RIPS_CARGAR:
                FrmCargarRIPS frmCargaRIPS = new FrmCargarRIPS();
                this.panPrincipal.add(frmCargaRIPS);
                frmCargaRIPS.setVisible(true);
                break;
            case RIPS_ADMINISTRAR:
                FrmAdministrarRIPS frmAdministrarRIPS = new FrmAdministrarRIPS(this);
                this.panPrincipal.add(frmAdministrarRIPS);
                frmAdministrarRIPS.setVisible(true);
                break;
            case ACERCA_DE:
                FrmAcercaDe frmAcercaDe = new FrmAcercaDe();
                this.panPrincipal.add(frmAcercaDe);
                frmAcercaDe.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "VALOR DE OPCION DESCONOCIDO");
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mbrPrincipal;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuItem mitAcercaDe;
    private javax.swing.JMenuItem mitAdministracion;
    private javax.swing.JMenuItem mitCarga;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
